### ISSUE TITLE
HBase conf not delegated correctly.

### ISSUE THREAD

**Issue by Patriko77** [ptgoetz/storm-hbase#4]
Hey man,

got really frustrated today, using your HBaseBolt. Looks like there is a bug when writing the hbase parameters to the HBaseConfiguration inside of org.apache.storm.hbase.bolt.HBaseBolt.

```
for(String key : conf.keySet()){
      hbConfig.set(key, String.valueOf(map.get(key)));
}
```

I think, this should be : 

```
for(String key : conf.keySet()){
      hbConfig.set(key, String.valueOf(conf.get(key)));
}
```

This way, I ended up having everything with value null ...

Greetz, Patrick

**Comment by ptgoetz** [comment]
fixed.
